name: almahbub_managment
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  sms_autofill: ^2.2.0
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  flutter_screenutil: ^5.6.0
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  pattern_formatter: ^2.0.0
  syncfusion_flutter_gauges: ^20.4.44
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  flutter_image_compress: ^1.1.3
  proste_indexed_stack: ^0.2.4
  focused_menu: ^1.0.5
  diamond_bottom_bar: ^1.0.0
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.2.17
  convex_bottom_bar: ^3.2.0
  flutter_share: ^2.0.0
  http: ^0.13.5
  fluttertoast: ^8.1.3
  video_player: ^2.5.1


#  Locatin
  yandex_mapkit: ^3.2.0
  osm_nominatim: ^2.0.1
  path_provider: ^2.0.11
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  dio: ^5.0.0


  #  Firebase
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_dynamic_links: ^5.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/svg/
     - assets/tr/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

